### ISSUE TITLE
Documentation for implementing the interfaces, particularly the pure method

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/functional#1]
In the documentation I can't find any examples of how I should implement interfaces like `gen:monad` and `gen:applicative`. 

In particular the `pure` method in `gen:applicative` doesn't seem to be documented properly, since the generic-interface version (the one I have to implement) takes two arguments, but the provided and documented version (`delayed-pure` in the internals) takes one argument.
```
gen:applicative: generic method definition has an incorrect arity; expected a procedure that accepts 2 arguments
  pure: #<procedure:my-type-pure>
```

**Comment by lexi-lambda** [comment]
Good catch. This library definitely needs a bit more love in the documentation department, so I’ll take a look and write some more docs.

**Comment by AlexKnauth** [comment]
Thanks!
